### PR TITLE
Fix core

### PR DESCRIPTION
**Pull request by carlkesselman**
There were a number of instances where the port number was not being passed through in the creation of Core objects and JavaObjects.  This would cause problems when start_headless was used with a non-default port argument.  This PR hopefully addresses all of the instances where this was the case.

### CODE REVIEW

**Comment by henrypinkard** [comment]
Looks good, thanks!

**Comment by henrypinkard** [comment]
Does this fix #402?

**Comment by carlkesselman** [comment]
Yes, I hope so.  I went through and hopefully found all of the instances where this was an issue.  One thing that I didn't do is that the timeout argument is not passed through consistently into JavaObject, but I didn't change the interfaces to address this.  I would be happy to do so if you think that would be useful.

Carl


Sent from my iPad

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA <x-apple-data-detectors://1/0>  90292-6695<x-apple-data-detectors://1/0>
Phone:  +1 (310) 448-9338<tel:+1%20(310)%20448-9338>
Email:  ***@***.******@***.***>
Web: http://www.isi.edu/~carl


On Apr 15, 2022, at 7:34 AM, Henry Pinkard ***@***.***> wrote:

﻿

Does this fix #402<https://github.com/micro-manager/pycro-manager/issues/402>?

**Comment by henrypinkard** [comment]
Yes, I think that would be a nice addition to keep everything consistent

**Pull request closed without merging**
