### PR TITLE
psf_viewer tutorial

### PR DESCRIPTION
**Pull request by wiebkejahr**
added jupyter notebook with psf viewer. added doc string to applications.rst

### CODE REVIEW

**Comment by henrypinkard** [comment]
Looks like you need to change the heading sizes within the notebook, since they are rendering incorrectly [here ](https://pycro-manager--212.org.readthedocs.build/en/212/applications.html)

**Comment by henrypinkard** [comment]
If you make another commit and push it, it will be automatically added to this PR

**Comment by wiebkejahr** [comment]
I hope that did the trick. I "downgraded" all headings, but they still show up [here](https://pycro-manager--212.org.readthedocs.build/en/212/applications.html)? Maybe needs a while to update, or do I need to recompile somewhere?

**Comment by henrypinkard** [comment]
Weird I couldn't get it to work either. I'll merge it and try to fix in a new PR

**Comment by henrypinkard** [comment]
Did you have a video showing this in action?

**Comment by wiebkejahr** [comment]
Cool thanks!
I'll acquire a video & screenshots some time next week and figure out how to include it.

I had actually been hoping for a GPU to arrive still such that the rendering looks more fluent, but it seems like I'm losing out against cyberpunk - I cannot even find a supplier that accepts orders from institutions :-D
So it's going to be crosssections only for the video - that's anyway how I will be using it.

**Pull request merged**
