### PR TITLE
Remove internal usage of `pycromanager.logging`

### PR DESCRIPTION
**Pull request by bruno-digitbio**
As described in #766, here we move towards a more canonical use of Python's `logging` module by having `pycromanager` sub-modules define their own loggers and use them.

We cannot remove the existing monkey-patch-based `pycromanager.logging` module yet, since it is public API surface and is used by `PyJavaZ`, and therefore it must be kept until at least[ those references ](https://github.com/PyJavaZ/PyJavaZ/blame/eef3202b33f9c3fd0f1f625e1fea0a065ecc7cce/pyjavaz/bridge.py#L16) are removed, but I went ahead and nuked the relevant documentation...happy to additionally (or instead) add any deprecation or other warnings to the corresponding functions to try to prevent future use until they are removed?

### CODE REVIEW

**Comment by bruno-digitbio** [comment]
Note that this PR was initially drafted based on the following search:

```bash
$ grep -R logging . | cut -d':' -f1 | sort | uniq | grep -v '\.git' | grep -v "Binary file"
./java/src/main/java/org/micromanager/remote/RemoteViewerStorageAdapter.java
./pycromanager.egg-info/SOURCES.txt
./pycromanager/acquisition/java_backend_acquisitions.py
./pycromanager/headless.py
./pycromanager/logging.py
```

**Comment by henrypinkard** [comment]
Bumped to the new version of pyjavaz so you should be good to build on that

**Comment by henrypinkard** [comment]
All set to merge this? The only other thing I see is to bump the minor version in `pycromanager/_version.py`. The new version will automatically build and deploy to pypi

**Comment by henrypinkard** [comment]
Thanks for all your work on this!

**Pull request merged**
