### PR TITLE
Add headless mode

### PR DESCRIPTION
**Pull request by henrypinkard**

### CODE REVIEW

**Comment by henrypinkard** [comment]
@tlambert03 

This was pretty straightforward and works on my mac (havent tested on windows). If you replace Pycromanager java with the [latest version](https://dl.bintray.com/micro-manager/micro-manager/org/micro-manager/pycro-manager/PycroManagerJava/0.20.2/) and do a pip upgrade you should be able to test it out. 

Example script: https://github.com/micro-manager/pycro-manager/blob/master/test/headless_demo.py

One remaining thing is specifying the right version of Java. I know the MM installer installs its own JRE, and this is the one that everything is tested on so it would be good to use this. Right now this code is equivalent to calling:

`java -classpath "/path/to/mm/jars/*" org.micromanager.remote.HeadlessLauncher`

I'm pretty sure you can specify a version of java by replacing `java` with `/path/to/java installation`. But I don't know how to figure out what the path java that the micro-manager installer adds is. @nicost do you know how to figure this out?

**Comment by tlambert03** [comment]
whoo hoo!  this is great, thank you!  will give it a try soon

**Comment by tlambert03** [comment]
not quite working for me yet... looks like some path stuff to figure out:

if I run the subprocess directly, it cannot find the headless launcher:

```sh
❯ java -classpath "/Applications/Micro-Manager-2.0.0-gamma1-20201220/plugins/Micro-Manager/*" org.micromanager.remote.HeadlessLauncher
Error: Could not find or load main class org.micromanager.remote.HeadlessLauncher
Caused by: java.lang.ClassNotFoundException: org.micromanager.remote.HeadlessLauncher
```

(note, my plugins folder has `Micro-Manager` (title case) instead of lower case `micro-manager` used in your command... but neither one made a difference)

some more info:
```
❯ which java
java is /usr/bin/java

❯ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

do I need to somehow compile `remote/HeadlessLauncher.java` first?  (please forgive the java naiveté)

**Comment by henrypinkard** [comment]
No, it is compiled within `PycroManagerJava-0.20.2.jar`, so you just need to make sure that is on your classpath.

My Java version is different, but seems unlikely this would be the culprit:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by nicost** [comment]
The date of the application folder is quite old. @tlambert03 did you install yesterday's nightly build (that should have @henrypinkard's latest changed)?

**Comment by henrypinkard** [comment]
You could try writing the name directly:

```
java -classpath "/Applications/Micro-Manager-2.0.0-gamma1/plugins/Micro-Manager/PycroManagerJava-0.20.2.jar:" org.micromanager.remote.HeadlessLauncher
```

This won't work because you haven't added the other jars in that folder. It gives the error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: mmcorej/CMMCore
	at org.micromanager.remote.HeadlessLauncher.main(HeadlessLauncher.java:19)
Caused by: java.lang.ClassNotFoundException: mmcorej.CMMCore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```

**Comment by henrypinkard** [comment]
Yes I think thats a good idea to update the build. You will still need to manually replace PycroManagerJava though in the new nightly build because I haven't pushed the new one yet

**Comment by henrypinkard** [comment]
From nico:

> A JRE is only provided on Windows, i.e. not on the Mac. On Windows the JRE is in the micro-manager installation folder /jre/bin/java.exe. The complete path on my system is /c/Program\ Files/Micro-Manager-2.0gamma/jre/bin/java.exe. Note that this does not tell you which version it is, although I guess you can figure it out by running it with the appropriate flags.

> Another way is looking at the contents of ImageJ.cfg. For me it says:
```
.
.\jre\bin\javaw.exe
-Dsun.java2d.dpiaware=false -Xmx2000m -XX:MaxDirectMemorySize=1000g -cp ij.jar ij.ImageJ
```
> This would also let you the same flags as used by Micro-Manager.

So it should be straightforward to add in to run using this java version automatically on windows systems.

For Mac, I guess you'll have to install the correct java manually, but I can write a little script to pull out the version that the libraries were compiled with to make installation of this easier

**Pull request merged**
