### PR TITLE
notebook example by Raymond Dunn

### PR DESCRIPTION
**Pull request by RaymondDunn**
Notebook example for headless closed-loop acquisition. Also included a short python module I wrote for peak finding, used in the example. Edited applications.rst to standardize on "pycro-manager" based on base repo readme.

### CODE REVIEW

**Comment by henrypinkard** [comment]
Cool! Looks like the notebook isn't correctly compiling into docs though. I'm guessing there's somewhere in the notebook that where the name of a specific kernel on your local system is specified, and the automatic build system doesn't have access to it. Maybe theres some way to remove that reference?


```

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbsphinx.py", line 1021, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbsphinx.py", line 832, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/client.py", line 524, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/client.py", line 482, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/client.py", line 394, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/jupyter_client/manager.py", line 571, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/jupyter_client/manager.py", line 262, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/jupyter_client/manager.py", line 181, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/jupyter_client/manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named Python 3.6.12 64-bit ('pycromanager': conda)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycro-manager/envs/164/lib/python3.7/site-packages/nbsphinx.py", line 1032, in parse
    str(e))
nbsphinx.NotebookError: NoSuchKernel in closedloop_headless_demo.ipynb:
No such kernel named Python 3.6.12 64-bit ('pycromanager': conda)

Notebook error:
NoSuchKernel in closedloop_headless_demo.ipynb:
No such kernel named Python 3.6.12 64-bit ('pycromanager': conda)
```

**Comment by RaymondDunn** [comment]
> I'm guessing there's somewhere in the notebook that where the name of a specific kernel on your local system is specified, and the automatic build system doesn't have access to it.

good catch I've never really dug into ipynb metadata. removed that ref

**Comment by henrypinkard** [comment]
It looks like you need to change the heading levels within your notebook. Right now they are all top level, which creates a bunch of [extra stuff in the table of contents](https://pycro-manager--164.org.readthedocs.build/en/164/applications.html)

Also, I think it might be good to note in the description in applications.rst that you've used this primarily for neuroscience (right?), but that it could be applied to other things as well

**Comment by henrypinkard** [comment]
Looks great. One last nitpicky thing: could you capitalize the c in "closed-loop" in the title of your notebook so its consistent with other applications?

**Comment by RaymondDunn** [comment]
not picky at all! I forgot to make those last edits - looks like i snuck them in just before your last msg

**Pull request merged**
