### PR TITLE
pass timeout into Bridge correctly

### PR DESCRIPTION
**Pull request by henrypinkard**

### CODE REVIEW

**Comment by ianhi** [comment]
i hink you missed one other `__new__` there are two there.

**Comment by henrypinkard** [comment]
Whoops https://github.com/micro-manager/pycro-manager/pull/391

**Comment by ianhi** [comment]
This looks like it breaks things. See: https://github.com/ianhi/pycro-plus-bridge/runs/5604379327?check_suite_focus=true

```
=================================== ERRORS ====================================
______________________ ERROR at setup of test_for_smoke _______________________
    @pytest.fixture(scope="session")
    def core() -> pycroCorePlus:
        mm_app_path = Path(find_micromanager())
>       start_headless(
            str(mm_app_path),
            str(mm_app_path / "MMConfig_demo.cfg"),
            timeout=5000,
            convert_camel_case=False,
        )
tests\test_pycro_plus_bridge.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\pycromanager\acq_util.py:90: in start_headless
    core = Core(timeout=timeout, **core_kwargs)
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\pycromanager\java_classes.py:84: in __new__
    bridge = Bridge(port=port, convert_camel_case=convert_camel_case, debug=debug, timeout=timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cls = <class 'pycromanager.bridge.Bridge'>, timeout = 5000
convert_camel_case = False, args = (), kwargs = {'debug': False, 'port': 4827}
port = 4827
    def __new__(cls, timeout: int=DEFAULT_TIMEOUT, convert_camel_case: bool=True,  *args, **kwargs):
        """
        Only one instance of Bridge per a thread/port combo
        """
        port = kwargs.get('port', Bridge.DEFAULT_PORT)
        if not hasattr(Bridge, 'local'):
            Bridge.local = threading.local()
        if not hasattr(Bridge.local, 'bridges'):
            Bridge.local.bridges = {}
        if port not in Bridge.local.bridges.keys():
            Bridge.local.bridges[port] = []
>           return super(Bridge, cls).__new__(cls, timeout=timeout, convert_camel_case=convert_camel_case,
                                              *args, **kwargs)
E           TypeError: object.__new__() takes exactly one argument (the type to instantiate)
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\pycromanager\bridge.py:224: TypeError
```

**Comment by ianhi** [comment]
what are you trying to accomplish wiht overriding new? is it essentially instancing? May be worthwhile giving https://python-patterns.guide/gang-of-four/singleton/ a read

**Pull request merged**
