### PR TITLE
add check for if tile_height and tile_width have been defined

### PR DESCRIPTION
**Pull request by ianhi**
`_tile_height` and `_tile_width` in `Dataset` are not garunteed to be defined, but they were still being used to reshape images which was leading to errors. Heres an example of how to reproduce the errors:

```python
from pycromanager import Bridge
from pycromanager import Acquisition, multi_d_acquisition_events

bridge = Bridge()
core = bridge.get_core()
mmStudio = bridge.get_studio()

z_pos = core.get_position()
z_delta = 3
z_start = z_pos - z_delta
z_end = z_pos + z_delta
z_step = 1
events = multi_d_acquisition_events(1,z_start= z_start, z_end = z_end,z_step=z_step, channel_group = 'UPLSAPO40X',channels=['BF', 'GFP'])
events = multi_d_acquisition_events(1,z_start= z_start, z_end = z_end,z_step=z_step,
                                    channel_group = 'UPLSAPO40X',channels=['BF', 'GFP'])
with Acquisition(directory='test', name='acq-test',post_hardware_hook_fn=f) as acq:
    acq.acquire(events)
dataset = acq.get_dataset()
dataset.read_image(z=5)
```

which leads to this error (slightly autoformatted by my editor bc I was derping around in the file):
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-6876a9f4c299> in <module>
----> 1 dataset.read_image(z=5)

~\miniconda3\envs\control\lib\site-packages\pycromanager\data.py in read_image(self, channel, z, time, position, channel_name, read_metadata, resolution_level, row, col, memmapped, **kwargs)
    813                 # if (self._tile_height is not None) and (self._tile_width is not None):
    814                 image = image[
--> 815                     (image.shape[0] - self._tile_height)
    816                     // 2 : -(image.shape[0] - self._tile_height)
    817                     // 2,

AttributeError: 'Dataset' object has no attribute '_tile_height'
```

I also changed the indexing of the shape because the height was being used for both width and height. (If this was wrong I'll rebase and drop the commit)

### CODE REVIEW

**Comment by ianhi** [comment]
This line could probably also use  the same treatment but I wasn't sure what to use instead of `tile_height` and `tile_width`:
https://github.com/micro-manager/pycro-manager/blob/2990c849ca6216913123331c6155f281087179fa/pycromanager/data.py#L592

**Comment by henrypinkard** [comment]
Are you doing this:


```
with Acquisition(directory='test', name='acq-test',post_hardware_hook_fn=f) as acq:
    acq.acquire(events)
dataset = acq.get_dataset()
dataset.read_image(z=5)
```


or this?
 
```
with Acquisition(directory='test', name='acq-test',post_hardware_hook_fn=f) as acq:
    acq.acquire(events)
    dataset = acq.get_dataset()
    dataset.read_image(z=5)
```

 the former is not recommended (and I would be surprised if it even works...), because after the `with` block, the acquisition should be cleaned up, and likewise its dataset, which is a java object. If youre trying to open data _after_ the acquisition is complete, you should open it by passing in the path to the constructor. This will be faster anyway bc data wont have to go through java python bridge

**Comment by ianhi** [comment]
I've been doing the former. With the changes in this PR that will work. Perhaps the acquistion object is not being properly cleaned up?

**Comment by henrypinkard** [comment]
I guess `acq` wouldnt be garbage collected yet since youre still holding a ref to it. Well, I guess you've discovered an unintended way of doing it, but if it works it works

**Comment by ianhi** [comment]
This also comes up if you don't use the acquisition as context manager. I started doing that because it allows you to peek into the data from python as it is being generated as `run_ac then the acquisition is no longer blocking.

**Comment by henrypinkard** [comment]
Yeah that makes sense

**Pull request merged**
