### PR TITLE
Add tutorial notebook for interactive microscopy control with ImJoy

### PR DESCRIPTION
**Pull request by oeway**
This PR adds a tutorial notebook for controlling microscopy interactively in a jupyter notebook with the [imjoy jupyter extension](https://github.com/imjoy-team/imjoy-jupyter-extension).

@henrypinkard Could you please do a proof reading? And also feel free to improve it.

Note, because of the issue I reported in https://github.com/micro-manager/pycro-manager/issues/90 the tutorial can be laggy and I hope we can do something about it.

### CODE REVIEW

**Comment by henrypinkard** [comment]
This looks great! 

I agree we should try to work out the snapImage lag. Will respond on that issue.

The only other thing that I think would be good to add is a few sentence summary of the scope of the things that are possible with ImJoy, which would be end up on [this page](https://pycro-manager.readthedocs.io/en/latest/examples.html)

**Comment by oeway** [comment]
> This looks great!
> 
> I agree we should try to work out the snapImage lag. Will respond on that issue.

Thanks! 

> 
> The only other thing that I think would be good to add is a few sentence summary of the scope of the things that are possible with ImJoy, which would be end up on [this page](https://pycro-manager.readthedocs.io/en/latest/examples.html)

Oh, I added into tutorials and the notebook is written as step by step to allow users to follow. I was thinking to make more advanced ImJoy app for the examples page. Or should I just move that into examples?

**Comment by henrypinkard** [comment]
Yes, even though the notebook itself is a tutorial, I think it makes more sense to have it in examples, since tutorials right now is all stuff that exists within pycromanager itself. Examples will be things built on top of pycromanager. Now that I think about it, it might make more sense to rename these sections: Examples --> Applications, and Tutorials --> Features. Would that make more sense? Any ideas for better names?

More advanced stuff would be great too. Wherever it ends up, I think make sure that there's a brief description on the top level link that will put it all into context for those that may not already be familiar with ImJoy

**Comment by oeway** [comment]
Yes, I think the renaming you propose makes more sense.

OK, I will try to do that.

**Comment by henrypinkard** [comment]
I'm thinking it makes sense to go ahead and merge this, and we can continue to work out the performance bottlenecks and maybe update a version later. What do you think?

If you agree, could you change it to instead push to the application section of the documentation? And also write up a couple sentences giving a description of notebooks like there are for the other[ applications](https://pycro-manager.readthedocs.io/en/latest/applications.html)

**Comment by oeway** [comment]
Sounds good, I will work get it ready soon.

**Comment by ianhi** [comment]
Just read through the tutorial, looks great and was definitely helpful for me!


> Jupyter notebook has little support for visualizing real-time data itself, but we can try to achieve live update by repeatitively clear the plot and draw again.

It hasn't be advertised super well but there is actually a fair amount of powerful functionality for live updates in jupyter notebooks. The widgets framework provided by [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/) works in both jupyter notebooks and jupyterlab and makes it very easy to forge a connection between python and a javascript frontend. It provides basic UI controls (buttons, dropdowns, sliders...), but also acts a basis on which to make custom widgets that connect python to javascript frontends.

Of particular relevance here is that there are two interactive matplotlib backends that work in the notebook so you can dynamically update and interact with the matplotlib plot. For example here's a video of manual image segmentation with a UI made from ipywidgets buttons, all running in a jupyter notebook: https://www.youtube.com/watch?v=aYb17GueVcU.

Though more to the point, you can use the `set_data` on the object returned by imshow to update the image. Which allows for things like thresholding an image:
thesholding

### equivalent matplotlib tutorial?

If you'd like I can make a tutorial equivalent to this one using interactive matplotlib in the notebook. Happy to hear your thoughts :)


### Dump of links in case you want to check out more:

- https://github.com/matplotlib/ipympl
- https://matplotlib.org/users/interactive.html?highlight=interactive%20backend#other-python-prompts
- https://jupyter.org/widgets

Things I've made/am making:
- https://mpl-interactions.readthedocs.io/en/latest/
   - Wraps lots of interactive matplotlib functionality to make it easy to use
- https://github.com/ianhi/ipysegment
   - Use browser canvas to manually segment (high performance), masks accessible as numpy arrays
- https://github.com/Hekstra-Lab/laser-pointer
  - click on image to aim a laser. Could be used as a general point selection tool
- https://github.com/ianhi/jupyter-microscopy

**Comment by ianhi** [comment]
I didn't post code for the thesholding example as it uses some obscure matplotlib functions so I actually just made that using mpl-interactions. But here is a stock ipywidgets + matplotlib example:

```python
%matplotlib ipympl
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
# precomputing all images
x = np.linspace(0,np.pi,200)
y = np.linspace(0,10,200)
X,Y = np.meshgrid(x,y)
parameter = np.linspace(-5,5)
example_image_stack = np.sin(X)[None,:,:]+np.exp(np.cos(Y[None,:,:]*parameter[:,None,None]))

plt.ioff()
fig = plt.figure()
plt.ion()
im = plt.imshow(example_image_stack[0])

def update(change):
    im.set_data(example_image_stack[change['new']])
    fig.canvas.draw_idle()
    
    
slider = widgets.IntSlider(value=0, min=0, max=len(parameter)-1)
slider.observe(update, names='value')
widgets.VBox([slider, fig.canvas])
```

### μmanager like hyperstack scrubbing

I've been meaning to do this for ages but I've been meaning to build a function that takes a numpy array (or dask or xarray or whatever) and makes μmanager style sliders to scrub through the hyperstack. I'm tracking that here: https://github.com/ianhi/mpl-interactions/issues/77 once thats implemented I'd also be willing to extract it's source code into an example for pycromanager if you'd like

**Comment by ianhi** [comment]
and finally: if you ever want to chat about maptlotlib in jupyternotebook or other ways make jupyter better for microscopy I'd be super happy to. Maybe we can figure out some stuff together that will make all our lives better

**Comment by henrypinkard** [comment]
Super cool @ianhi!

I think a lot of what you describe would be great additions. There aren't yet any application examples on the opening/analyzing data side. Definitely the hyperstack scrubber would be awesome. I also really like the segmentation (I wish I had know about this 6 months ago when I was doing a ton of that), and I think MPL contrast controllers look a bit cleaner/more intuitive than than the ITK/VTK. Up to @oeway whether any changes are incorporated here, but you should definitely open Issues/PRs for additional things you'd like to add

**Comment by oeway** [comment]
Hi @ianhi Thanks for pointing out and it seems you had done great job along these lines, cool!

Yes, ipywidgets and your mpl-interactions is very much relevant here. In fact, when I say it provide limited interactivity, I meant Jupyter notebook itself, without additional extensions. But I do agree that I should perhaps explain a bit more, please check the updated notebook, we now have:
> While we can see the live stream, it provides litte interactivity, for example, if we want to do contrast stretching, we will have to stop the stream and change the code. [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/) is a Jupyter extension that designed for adding basic control elements (e.g. buttons and sliders) to control python code execution. There are also other similar extensions such as [mpl-interactions](https://mpl-interactions.readthedocs.io/en/latest/), and you can find more in [widgets](https://jupyter.org/widgets) (thanks to @ianhi). 

> In addition to these existing options, we built [imjoy-jupyter-extension](https://github.com/imjoy-team/imjoy-jupyter-extension) that utilizes the ImJoy framework to introduce interactivity to Jupyter notebooks. It allows Python code to interact web UI directly without making dedicated Jupyter widgets in Python. It simplify the development of UI widgets, improve code reuse, and users can simply refer to an URL to extend the UI.

> In the following section, we will show you how we can achieve better interactivity by building an ImJoy plugin.

Is this better explained to you? I didn't change it to `ipympl` backend with `set_data` and introduce ipywidgets because I try to make the tutorial simple and easier to understand. And you might want to open another PR to add another tutorial which uses the widgets you made.

About Jupyter widgets vs ImJoy plugins, we use the same jupyter comm communication protocol to support interaction, but with very different way of building UI. Basic ipywidgets is suitable for users who want to build simple UI and don't want to touch JS/HTML/CSS. For more complex UI, for example, to show a device property browser as we have in the last example, you can build more advanced widgets (such as those in [widgets](https://jupyter.org/widgets)), but that will require more understanding of the MVC concept in jupyter. The ImJoy extension simplify the entire process for building complex UI by providing [imjoy-rpc](https://github.com/imjoy-team/imjoy-rpc), so you can build ImJoy plugins in pure JS/HTML/CSS. You can expose api functions in JS and it can be transparently called in Python. Like this we can maximize the code reuse and allow the UI tools also usable outside Jupyter notebooks. There are other advantages such as sandboxing of UI elements, support google Colab.

See a few examples which can run as an independent app and a imjoy plugin that runs inside a notebook (click the launch binder icon if you want to try):
https://github.com/imjoy-team/kaibu/
https://github.com/imjoy-team/imagej.js/
https://github.com/hms-dbmi/vizarr/

I like the idea of working together If you are interested, we should perhaps schedule a meeting?

@henrypinkard I added the summary, please check it out.

**Comment by henrypinkard** [comment]
Looks great! Ready to merge?

**Comment by oeway** [comment]
Yes, let's merge it, and we can improve it further with other PR.

**Comment by henrypinkard** [comment]
Looks like it is not quite rendering correctly. It's got different formatting than the others in the title and adds an extraneous example. Maybe you've got multiple top level headers?

https://pycro-manager.readthedocs.io/en/latest/applications.html

**Comment by henrypinkard** [comment]
And the link isn't rendered properly

**Comment by ianhi** [comment]
> Looks like it is not quite rendering correctly. 
@henrypinkard  I'd recommend enabling the readthedocs github action. Then on every push to a PR readthedocs will try to build it an give a link to the artifact that you click on to view the rendered version. You can enable it like this:

image
 for example:
image
leads to a fully rendered version: https://mpl-interactions--107.org.readthedocs.build/en/107/

**Comment by henrypinkard** [comment]
Good idea, i added

**Pull request merged**
